FROM nginx:1.15.8-alpine
#   configuration
# https://www.digitalocean.com/community/tutorials/nginx-location-directive 
copy ./nginx.conf /etc/nginx/nginx.conf



#content, comment out the ones you dont need!
copy ./*.html /usr/share/nginx/html/
copy ./assets/styles/*.css /usr/share/nginx/html/assets/styles/
copy ./assets/scripts/*.js /usr/share/nginx/html/assets/scripts/